// packages/vue/src/components/TextField.vue
<script setup lang="ts">
import { encodeProps } from '../encode.js';

// Array-form props (no runtime type → no Boolean coercion, so absent props
// stay undefined and are omitted, matching the React/Svelte serializers).
// `style` is declared here so Vue never treats it as the DOM style attribute.
defineOptions({ inheritAttrs: false });
const props = defineProps(['name', 'value', 'placeholder', 'width', 'height', 'multiline', 'password', 'readOnly', 'maxLength', 'fontSize', 'style']);
</script>

<template>
  <forme-text-field :props="encodeProps('TextField', props)"></forme-text-field>
</template>

// packages/svelte/src/components/TextField.svelte
<script lang="ts">
  import type { Style } from '@formepdf/shared';
  import { encodeProps } from '../encode.js';

  interface Props {
    /** Unique field name (used as the PDF field identifier). */
    name: string;
    /** Pre-filled value. */
    value?: string;
    /** Placeholder text shown when empty. */
    placeholder?: string;
    /** Field width in points. */
    width: number;
    /** Field height in points. Default: 24. */
    height?: number;
    /** Allow multi-line input. Default: false. */
    multiline?: boolean;
    /** Mask input as password. Default: false. */
    password?: boolean;
    /** Prevent editing. Default: false. */
    readOnly?: boolean;
    /** Maximum number of characters. */
    maxLength?: number;
    /** Font size in points. Default: 12. */
    fontSize?: number;
    style?: Style;
  }

  let rest: Props = $props();
</script>

<forme-text-field props={encodeProps('TextField', rest)}></forme-text-field>
